name: Publish latest image to GitHub docker image registry

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check if current release is latest
        run: echo "##[set-output name=is_latest;]$(sh .github/is-latest-release.sh)"
        id: release
      - name: Publish to Registry
        if: steps.release.outputs.is_latest == 'true'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: meilisearch/github-issues-scraper/github-issues-scraper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
